name: Build APK
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List files
        run: ls -R
      - name: Set script permissions
        run: chmod +x ./build_apk.sh
      - name: Build
        run: bash ./build_apk.sh
